function [BUS_PV,FORECASTP_PV,FORECASTQ_PV, CAPACITY_PV, PF_PV, ...
  DETPMIN_PV, DETPMAX_PV ,DETPMEAN_PV,DETPSIGMA_PV] = idx_pv

BUS_PV       = 1;
FORECASTP_PV = 2;
FORECASTQ_PV = 3;
CAPACITY_PV  = 4;
PF_PV        = 5;
DETPMIN_PV   = 6;
DETPMAX_PV   = 7;
DETPMEAN_PV = 8;
DETPSIGMA_PV = 9;

